### ISSUE TITLE
Må oppdatere siden for at teksten skal endres

### ISSUE THREAD

**Issue by nietsrot** [V1adau/erdethelg#1]
Teksten som viser hvorvidt det er helg ("Nei", "Det nærmer seg"...) endres kun når siden lastes på nytt når maskinen har stått i dvale når endringen skulle ha skjedd (ikke testet å la maskinen stå på hele uken). Upraktisk for oss som har denne på egen skjerm hele uken men setter maskinen i dvale når man går fra jobb, ettersom det trengs egen plugin i nettleser for å sikre at man alltid har den mest oppdaterte informasjonen om hvorvidt det nærmer seg helg eller ikke.

Kun testet i Chrome.

**Comment by V1adau** [comment]
Takk for god tilbakemelding! Jeg skal ta en titt på det så snart jeg får litt tid!

**Comment by V1adau** [comment]
Dette problemet skal være fikset i 7f71b763573560583605e17f27d767e383b02966!
